# musicbox_1.yaml

substitutions:
  device_name: "esphome-web-47a1fc"
  friendly_name: "MusicBox 1"
  media_player_entity_id: "media_player.${ friendly_name | lower | replace(' ', '_') }"
  weather_forecast_id: weather.forecast_home

esphome:

logger:
  level: DEBUG
  logs:
    xpt2046: INFO
    esp-idf.httpd: ERROR
    sendspin.player: ERROR    

packages:
  # Holt die Grundfunktionen (WLAN, API, etc.)
  base: !include common/base-s3_devkitc_1.yaml
  hardware: !include musicbox/hardware.yaml
  functions: !include musicbox/main.yaml

