# musicbox_B.yaml

substitutions:
  device_name: "esphome-web-46406c"
  friendly_name: "MusicBox B"
  media_player_entity_id: "media_player.${ friendly_name | lower | replace(' ', '_') }"
  weather_forecast_id: weather.forecast_home

logger:
  level: DEBUG
  logs:
    # xpt2046: INFO

wifi:
  id: wifi_id
  ssid: "Home"
  password: "Spellfireisnothere"
  ap: 
    ssid: "${friendly_name} Fallback"
    password: "ESPHome12345"

captive_portal:


packages:
  # Holt die Grundfunktionen (WLAN, API, etc.)
  base: !include common/base-s3_devkitc_1.yaml
  hardware: !include musicbox/hardware.yaml
  functions: !include musicbox/main.yaml

