# musicbox_1.yaml

substitutions:
  device_name: "esphome-web-479ce4"
  friendly_name: "MusicBox 2"
  media_player_entity_id: "media_player.${ friendly_name | lower | replace(' ', '_') }"
  weather_forecast_id: weather.forecast_home

  # ========================================================
  # --- LINKE SEITE: (3V3) DISPLAY/TOUCH, Drehimpulsgeber --
  # ========================================================
  # Optimierung Pins
  # --- BLOCK 1: KY-040 Drehgeber (Ganz oben am ESP32) ---
  pin_encoder_clk:   GPIO4   # ESP32: J1-4  -> Geht an: KY-040 CLK
  pin_encoder_dt:    GPIO5   # ESP32: J1-5  -> Geht an: KY-040 DT
  pin_encoder_sw:    GPIO6   # ESP32: J1-6  -> Geht an: KY-040 SW

  # --- BLOCK 2: Touch & Display (Spiegelbildlich zum Display-Header) ---
  # (Hinweis: Display SD_CS lassen wir frei oder legen es auf einen freien Pin)
  pin_touch_irq:     GPIO7   # ESP32: J1-7  -> Geht an: CTP_INT
  pin_i2c_sda:       GPIO15  # ESP32: J1-8  -> Geht an: CTP_SDA
  pin_touch_reset:   GPIO16  # ESP32: J1-9  -> Geht an: CTP_RST
  pin_i2c_scl:       GPIO17  # ESP32: J1-10 -> Geht an: CTP_SCL

  # --- BLOCK 3: Hardware-SPI & Display-Steuerung ---
  # (Hinweis: ESP32 J1-13 [GPIO3] und J1-14 [GPIO46] überspringen )


  pin_display_dc:     GPIO08  # J1-12 -> D10 LCD_RS (DC)
  pin_display_reset:  GPIO09  # J1-15 -> D11 LCD_RST
  pin_display_cs:     GPIO10  # J1-16 -> D12 LCD_CS
  pin_spi_mosi:       GPIO11  # J1-17 -> D09 SDI(MOSI)
  pin_spi_clk:        GPIO12  # J1-18 -> D08 SCK
  pin_spi_miso:       GPIO13  # J1-19 -> D06 SDO(MISO)
  pin_display_led:    GPIO14  # J1-20 -> D07 LED
  # ========================================================
  # --- RECHTE SEITE (5V): AUDIO, LED  ---
  # ========================================================

  # --- WS2812 RGB-LED ---
  # 5V                       # -> +5V
  pin_ws2812_din:    GPIO01  # -> DIN
  # GND                      # -> GND

  # --- MAX98357 I2S Audio Block ---
  pin_max98357_lrc:  GPIO41  # -> LRC
  pin_max98357_bclk: GPIO40  # -> BCLK
  pin_max98357_din:  GPIO39  # -> DIN
  # 100kOhm gegen GND        # -> GAIN
  # frei für stereo          # -> SD
  # GND                      # -> GND
  # 5V                       # -> VIN


esphome:

wifi:
  power_save_mode: NONE
  output_power: 19.5dBm

logger:
  level: DEBUG
  logs:
    xpt2046: INFO
    esp-idf.httpd: ERROR
    sendspin.player: ERROR    

packages:
  # Holt die Grundfunktionen (WLAN, API, etc.)
  base: !include common/base-s3_devkitc_1.yaml
  illuminance: !include common/bh1750.yaml
  display: !include common/ST7796TSFT6336U.yaml
  sound: !include common/MediaPlayerSendspin.yaml
  light: !include common/LedStripOnboard.yaml
  hardware: !include musicbox/hardware.yaml
  functions: !include musicbox/main.yaml

