# speaker_4.yaml
substitutions:
  name: "esphome-web-15bb2c"
  friendly_name: "Smart Speaker 4"
  version: "0.5.0"
  media_player_entity_id: "media_player.${ friendly_name | lower | replace(' ', '_') }_audio_player"

packages:
  # Holt die Grundfunktionen (WLAN, API, etc.)
  core: !include common/base-esp32.yaml
  # Holt die hardwarespezifischen Sensoren/Relais
  hardware: !include common/test0.yaml

