# speaker_5.yaml

substitutions:
  device_name: "esphome-web-46406c"
  friendly_name: "Smart Speaker 5"
  media_player_entity_id: "media_player.${ friendly_name | lower | replace(' ', '_') }"
  weather_forecast_id: weather.forecast_home

logger:
  level: DEBUG
  logs:
    xpt2046: INFO

packages:
  # Holt die Grundfunktionen (WLAN, API, etc.)
  base: !include common/base-s3_devkitc_1.yaml
  hardware: !include musicbox/hardware.yaml
  functions: !include musicbox/main.yaml

