# speaker_4.yaml
substitutions:
  device_name: "esphome-web-15bb2c"
  friendly_name: "Smart Speaker 4"
  media_player_entity_id: "media_player.${ friendly_name | lower | replace(' ', '_') }_audio_player"

packages:
  # Holt die Grundfunktionen (WLAN, API, etc.)
  base: !include common/base-esp32.yaml
  # Holt die Funktionalität
  functions: !include common/voice-satellite.yaml
  environment: !include common/bme280.yaml
  scripts: !include common/scripts.yaml

