# musicbox/hardware.yaml

# -------------------------------------------------------------------
# Virtual
# -------------------------------------------------------------------

time:
  - platform: sntp
    id: my_time
    timezone: "Europe/Berlin"

button:
  - platform: restart
    name: "Restart"
    icon: mdi:restart
    on_press:
      then:
        - safe_mode.mark_successful

switch:
  - platform: template
    id: ha_switch_power
    name: "Eingeschaltet"
    icon: mdi:power
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

sun:
  latitude: !secret latitude
  longitude: !secret longitude


external_components:
  - source:
      type: local
      path: my_components
    components: 
      - my_moon
      - sendspin

# -------------------------------------------------------------------
# Sensoren
# -------------------------------------------------------------------
text_sensor:
  # 📡 Spiegelt die Wetter- und Umweltdaten aus deinem Home Assistant
  - platform: homeassistant
    id: ha_weather
    name: "WetterH"
    entity_id: weather.home
  - platform: sun
    id: my_sunrise
    name: "Aufgang"
    type: sunrise
    format: "%H:%M"
  - platform: sun
    id: my_sunset
    name: "Untergang"
    type: sunset
    format: "%H:%M"
  - platform: my_moon
    id: my_moonphase
    name: "MondphaseY"
    update_interval: 10min

  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "SSID"
    # scan_results:
    #   name: Latest Scan Results
    power_save_mode:
      name: Wifi Power Save Mode

sensor:
  - platform: homeassistant
    id: weather_temperature
    entity_id: ${weather_forecast_id}
    attribute: temperature
    unit_of_measurement: "°C"
  - platform: homeassistant
    id: weather_humidity
    entity_id: ${weather_forecast_id}
    attribute: humidity
    unit_of_measurement: "%"
  - platform: homeassistant
    id: weather_pressure
    entity_id: ${weather_forecast_id}
    attribute: pressure
    unit_of_measurement: "hPa"
  - platform: homeassistant
    id: weather_wind_speed
    entity_id: ${weather_forecast_id}
    attribute: wind_speed
    unit_of_measurement: "km/h"
  - platform: homeassistant
    id: weather_wind_bearing
    entity_id: ${weather_forecast_id}
    attribute: wind_bearing
    unit_of_measurement: "°"
  - platform: homeassistant
    id: weather_wind_gust_speed
    entity_id: ${weather_forecast_id}
    attribute: wind_gust_speed
  - platform: homeassistant
    id: weather_uv_index
    entity_id: ${weather_forecast_id}
    attribute: uv_index

  - platform: rotary_encoder
    id: my_encoder_pulse
    pin_a:
      number: ${pin_encoder_clk}
      mode: INPUT_PULLUP
    pin_b:
      number: ${pin_encoder_dt}
      mode: INPUT_PULLUP
    resolution: 1
    publish_initial_value: true
    filters:
      - debounce: 50ms
      - throttle: 50ms

binary_sensor:
  - platform: gpio
    id: my_encoder_button
    pin:
      number: ${pin_encoder_sw}
      inverted: true
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 20ms
    
light:
# Display Backlight (PWM)
  - platform: monochromatic
    id: display_backlight
    output: backlight_pwm
    name: "Display Hintergrundbeleuchtung"
    restore_mode: RESTORE_DEFAULT_ON
              
output:
  - platform: ledc
    pin: ${pin_display_led}
    id: backlight_pwm
    min_power: 0%
    max_power: 80%
    frequency: 1000Hz # Angenehme Frequenz, um kein hörbares Spulenfiepen zu erzeugen



