# musicbox/main.yaml

esphome:
  project:
    name: "hufi.musicbox"
    version: "0.0.3"
  on_boot:
    - priority: -100
      then:
        - lambda: |-
            //id(set_page_index).execute(${PAGE_BOOT});
            id(is_blocked) = true;

esp32:
  framework:
    # Das begrenzt den RAM-Verbrauch des WLAN-Stacks auf dem alten ESP32 massiv
    sdkconfig_options:
      CONFIG_LWIP_MAX_ACTIVE_TCP_CONNECTIONS: "5"
      CONFIG_LWIP_MAX_SOCKETS: "7"

logger:
  level: DEBUG


### Bedienung ###
# Pages: Konstanten als Substitution, niemals die int verwenden
# PAGE_BOOT:      0
# PAGE_IDLE:      1
# PAGE_MEDIA:     2
# PAGE_VOLUME:    3
# PAGE_LIGHT:     4
# PAGE_SETTINGS:  5
# PAGE_SHUTDOWN:  99
#
# Rotary:
# Wheel: Wechsel zwischen den Pages 1..5
# Click: Page aktivieren
# nach 15 sec Inaktivität wird die Seite PAGE_IDLE/PAGE_MEDIA aktiviert, je nachdem ob der media_player läuft
# 
# Page aktiviert:
# PAGE_BOOT: geht nicht, verschwindet, wenn time_sync erreicht
# PAGE_IDLE: Wechsel der Subpages "Time,Date,Weekday", "Weather forecast", "Sunrise/set", "Moonphase"
# Page_MEDIA: Play/Pause, Stop, FR/FF, Next/Previous Track
# Page_VOLUME: Volume up/down, Mute
# Page_LIGHT: Auswahl des Light effects
# Page_SETTINGS: Auswahl der Subpages "Light brightness" "Backlight brightness"






binary_sensor:
  - platform: gpio
    pin:
      number: ${rotary_btn_pin}
      mode: INPUT
      inverted: true
    id: rotary_button
    on_click:
      then:
        - logger.log: "Button Clicked"
        - script.execute:
            id: on_page_activate
            index: !lambda "return id(current_page_index);"
            
sensor:
  # Physischer Drehencoder für die Modus-Aktionen (Rechts- und Linksdrehen)
  - platform: rotary_encoder
    id: encoder_pulses
    pin_a: ${rotary_a_pin}
    pin_b: ${rotary_b_pin}
    publish_initial_value: true
    on_clockwise:
      then:
        - logger.log: "Clockwise -> Next"
        - script.execute:
            id: set_page_index
            index: !lambda "return id(current_page_index) + 1;"
    on_anticlockwise:
      then: 
        - logger.log: "Anticlockwise _> Prev"
        - script.execute:
            id: set_page_index
            index: !lambda "return id(current_page_index) - 1;"

  # Wifi Signalstärke
  - platform: wifi_signal
    id: wifi_rssi
    name: "Signalstärke"
    update_interval: 15s
    on_value:
      then:
        # Ausgezeichnetes Signal
        - if:
            condition:
              lambda: 'return x >= -50.0f;'
            then:
              - lvgl.image.update:
                  id: widget_wifi_icon # <-- Hier angepasst
                  src: img_wifi_4
                  
        # Gutes Signal
        - if:
            condition:
              lambda: 'return x < -50.0f && x >= -65.0f;'
            then:
              - lvgl.image.update:
                  id: widget_wifi_icon
                  src: img_wifi_3

        # Normales Signal
        - if:
            condition:
              lambda: 'return x < -65.0f && x >= -75.0f;'
            then:
              - lvgl.image.update:
                  id: widget_wifi_icon
                  src: img_wifi_2

        # Schlechtes Signal
        - if:
            condition:
              lambda: 'return x < -75.0f && x >= -85.0f;'
            then:
              - lvgl.image.update:
                  id: widget_wifi_icon
                  src: img_wifi_1

        # Kein/Sehr schlechtes Signal (oder Offline)
        - if:
            condition:
              lambda: 'return x < -85.0f || isnan(x);'
            then:
              - lvgl.image.update:
                  id: widget_wifi_icon
                  src: img_wifi_0

time:
  - platform: homeassistant
    id: esptime
    on_time_sync:
      - lambda: |-
          ESP_LOGI("time", "on_time_time_sync");

          if (id(is_blocked)) {
            ESP_LOGI("time", "Systemstart abgeschlossen");
            id(is_blocked) = false;
            id(set_page_index).execute(${PAGE_IDLE}); 
          }

    # Aktualisiert die Anzeige jede Sekunde
    on_time:
      - seconds: /1
        then:
          - lvgl.label.update:
              id: label_time
              text: !lambda |-
                return id(esptime).now().strftime("%H:%M:%S");
          - lvgl.label.update:
              id: label_date
              text: !lambda |-
                return id(esptime).now().strftime("%d.%m.%Y");
          - lvgl.label.update:
              id: label_weekday
              text: !lambda |-
                const char* days[] = {"Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"};
                return days[id(esptime).now().day_of_week - 1];

text_sensor:
  - platform: homeassistant
    id: player_title
    entity_id: media_player.smart_speaker_2_audio_player_2
    attribute: media_title
    on_value:
      then:
        - logger.log:
            format: "title %s"
            args: 'x.c_str()'
        - lvgl.label.update:
            id: label_title
            text: !lambda |-
              return x.c_str();

  - platform: homeassistant
    id: player_artist
    entity_id: media_player.smart_speaker_2_audio_player_2
    attribute: media_artist
    on_value:
      then:
        - logger.log:
            format: "artist %s"
            args: 'x.c_str()'
        - lvgl.label.update:
            id: label_artist
            text: !lambda |-
              return x.c_str();

  - platform: homeassistant
    id: player_album_name
    entity_id: media_player.smart_speaker_2_audio_player_2
    attribute: media_album_name
    on_value:
      then:
        - logger.log:
            format: "album_name %s"
            args: 'x.c_str()'
        - lvgl.label.update:
            id: label_album
            text: !lambda |-
              return x.c_str();

  - platform: homeassistant
    id: player_album_art
    entity_id: media_player.smart_speaker_2_audio_player_2
    attribute: entity_picture
    on_value:
      then:
        - logger.log:
            format: "album_art %s"
            args: 'x.c_str()'
        # Wir nutzen ein allgemeines Lambda statt der fertigen 'set_url'-Aktion
        - lambda: |-
            // 1. Wenn die URL leer ist, brechen wir das Lambda sofort ab.
            // Es wird KEIN Download-Befehl an die Komponente gesendet!
            if (x.empty() || x == "null") {
              ESP_LOGD("custom", "URL ist leer. Überspringe HTTP-Client-Initialisierung.");
              return;
            }

            // 2. Pfade prüfen
            bool is_local_ip = (x.rfind("http://192.168.", 0) == 0);
            bool is_local_path = (x.rfind("/api/", 0) == 0);

            std::string final_url;
            if (is_local_ip || is_local_path) {
              ESP_LOGD("custom", "Lokales Bild erkannt. Lade direkt.");
              final_url = x;
            } else {
              ESP_LOGD("custom", "Externes Bild erkannt. Nutze wsrv.nl Proxy.");
              final_url = "https://wsrv.nl?url=" + x + "&w=100&h=100&fit=cover&output=jpg";
            }

            // 3. Hier steuern wir das Online-Image direkt über seine C++ Instanz an.
            // Das entspricht exakt der YAML-Aktion, aber absolut sicher gekapselt.
            id(cover_image).set_url(final_url);
            id(cover_image).update();

http_request:
  timeout: 10s
  useragent: esphome/musicbox
  # Korrekte ESPHome-Variablen zur RAM-Begrenzung:
  buffer_size_rx: 512
  buffer_size_tx: 256

image:
  - platform: online_image
    url: "https://wsrv.nl"
    id: cover_image
    format: JPG
    type: RGB565
    on_download_finished:
        - lvgl.image.update:
            id: widget_cover_image
            src: cover_image
        - lambda: |-
            if (cached) {
              ESP_LOGD("online_image", "Cache hit: using cached image");
            } else {
              ESP_LOGD("online_image", "Cache miss: fresh download");
            }
    on_error:
        - lambda: |-
            ESP_LOGE("cover", "Download error");

    resize: 100x100
  - platform: file
    file: "mdi:music-box-outline"
    id: img_boot_logo
    type: BINARY
    resize: 64x64
  - platform: file
    file: "mdi:wifi-strength-outline"
    id: img_wifi_0
    type: BINARY
    resize: 32x32
  - platform: file
    file: "mdi:wifi-strength-1"
    id: img_wifi_1
    type: BINARY
    resize: 32x32
  - platform: file
    file: "mdi:wifi-strength-2"
    id: img_wifi_2
    type: BINARY
    resize: 32x32
  - platform: file
    file: "mdi:wifi-strength-3"
    id: img_wifi_3
    type: BINARY
    resize: 32x32
  - platform: file
    file: "mdi:wifi-strength-4"
    id: img_wifi_4
    type: BINARY
    resize: 32x32


# Backlight (PWM)
output:
  - platform: ledc
    pin: GPIO22
    id: backlight_pwm
    frequency: 1000Hz # Angenehme Frequenz, um kein hörbares Spulenfiepen zu erzeugen
light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Hintergrundbeleuchtung"
    id: display_backlight
    restore_mode: RESTORE_DEFAULT_ON

# Gemeinsamer SPI-Bus für Display & Touch
spi:
  id: bus_spi
  clk_pin: ${display_sck_pin}
  mosi_pin: ${display_mosi_pin}
  miso_pin: ${display_miso_pin}

# TFT Display
font:
  - file: "gfonts://Roboto"
    id: roboto_font_small
    size: 20
  - file: "gfonts://Roboto"
    id: roboto_font
    size: 30
  - file: "gfonts://Roboto"
    id: roboto_font_large
    size: 40
  - file: "gfonts://Roboto"
    id: roboto_font_huge
    size: 50

display:
  - platform: ili9xxx
    model: ILI9341
    id: tft_display
    cs_pin: ${display_cs_pin}
    dc_pin: ${display_dc_pin}
    reset_pin: ${display_rst_pin}
    invert_colors: false
    auto_clear_enabled: false
    transform:
      swap_xy: true
      mirror_x: true
      mirror_y: true
    dimensions:
      height: 240
      width: 320

lvgl:
  id: my_lvgl
  displays:
    - tft_display
  buffer_size: 10% 

  theme:
    dark_mode: true

  # Der Top Layer ist auf allen Pages sichtbar
  top_layer:
    widgets:
      - obj:
          x: 0
          y: 0
          width: 100%
          height: 40
          bg_color: 0x222222
          text_color: "0xFFFF00"
          text_font: roboto_font_small
          widgets:
            - label:
                id: widget_title_label
                align: LEFT_MID
                x: 10
                width: 200
                text: "Title"
            - image:
                id: widget_wifi_icon
                src: img_wifi_0
                align: RIGHT_MID
                x: -10
                width: SIZE_CONTENT
                height: SIZE_CONTENT
                recolor: 0xFFFFFF
                recolor_opa: 100%
  pages:
    - id: page_boot
      widgets:
        # 1. Das zentrale Musik-Logo
        - image:
            id: boot_logo
            src: img_boot_logo
            align: CENTER
            y: -20 # Leicht nach oben versetzt
            recolor: 0xFFFFFF # Weiß einfärben
            recolor_opa: 100%

        # 2. Ein animierter Ladekreis (Spinner) um das Logo herum
        - spinner:
            id: boot_spinner
            align: CENTER
            y: -20
            width: 110
            height: 110
            spin_time: 1000ms
            arc_length: 60
            
        # 3. Der Statustext darunter
        - label:
            id: label_boot_status
            text: "System startet..."
            align: CENTER
            text_color: "0xFFFFFF" # Weiße Schrift
            y: 70

        # 4. Systeminfos ganz unten (nebeneinander oder untereinander)
        - label:
            id: label_version_proj
            align: CENTER
            y: 260
            width: 300
            text_color: "0xFFFFFF" # Weiße Schrift
            text_font: montserrat_14
            # Das Widget holt sich seine Informationen vollautomatisch selbst!
            text: !lambda |-
              return "App: " + std::string(ESPHOME_PROJECT_NAME) + " v" + std::string(ESPHOME_PROJECT_VERSION);

        - label:
            id: label_version_sys
            align: CENTER
            y: 280
            width: 300
            text_color: "0xFFFFFF" # Weiße Schrift
            text_font: montserrat_14
            text: !lambda |-
              return "ESPHome: " + std::string(ESPHOME_VERSION);

    - id: page_idle
      widgets:
        # Große Uhrzeit in der Mitte
        - label:
            id: label_time
            text: "--:--:--"
            x: 10
            y: 60
            width: 300
            text_color: "0xFFFFFF"
            text_font: montserrat_48
            text_align: CENTER

        # Datum unter der Uhrzeit
        - label:
            id: label_date
            text: "--.--.----"
            x: 10
            y: 150
            width: 300
            text_color: "0xAAAAAA" # Graue Schrift
            text_font: montserrat_30
            text_align: CENTER  

        # Wochentag unter dem Datum
        - label:
            id: label_weekday
            text: "Wochentag"
            x: 10
            y: 180          # Platziert unter dem Datum
            width: 300
            text_color: "0xAAAAAA" # Graue Schrift
            text_font: montserrat_30
            text_align: CENTER            
    - id: page_media
      widgets:
        # Text-Label für den Album/Station (Über dem Songtitel)
        - label:
            id: label_album
            text: "-"
            x: 10
            y: 40
            width: 300
            long_mode: SCROLL
            text_color: "0xFFFF00" # Gelbe Schrift
            text_font: montserrat_18
            text_align: CENTER

        # Text-Label für den Songtitel (Rechts neben dem Bild)
        - label:
            id: label_title
            text: "Keine Wiedergabe"
            x: 10
            y: 60
            width: 300
            long_mode: SCROLL
            text_color: "0xFFFFFF" # Weiße Schrift
            text_font: montserrat_32
            text_align: CENTER

        # Text-Label für den Interpreten (Unter dem Songtitel)
        - label:
            id: label_artist
            text: "-"
            x: 10
            y: 90
            width: 300
            long_mode: SCROLL
            text_color: "0xAAAAAA" # Graue Schrift für besseren Kontrast
            text_font: montserrat_28
            text_align: CENTER
        - image:
            id: widget_cover_image
            src: cover_image
            x: 100
            y: 140
            width: 100
            height: 100
    - id: page_volume
      widgets:
        # Titel oben
        - label:
            text: "Volume"
            x: 10
            y: 50
            width: 300
            text_color: "0xFFFFFF"
            text_font: montserrat_30
            text_align: CENTER

        # Große Prozentanzeige in der Mitte
        - label:
            id: label_volume_pct
            text: "0 %"
            x: 10
            y: 120
            width: 300
            text_color: "0x0000FF" # Gelb
            text_font: montserrat_30
            text_align: CENTER

        # Visueller Slider / Fortschrittsbalken
        - slider:
            id: volume_slider
            x: 35
            y: 180
            width: 250
            height: 20
            min_value: 0
            max_value: 100
            value: 42
    - id: page_light
    - id: page_settings
    - id: page_shutdown






substitutions:
  PAGE_BOOT:      0
  PAGE_IDLE:      1
  PAGE_MEDIA:     2
  PAGE_VOLUME:    3
  PAGE_LIGHT:     4
  PAGE_SETTINGS:  5
  PAGE_SHUTDOWN:  6



globals:
  - id: page_text
    type: std::vector<std::string>
    initial_value: '{"BOOT", "IDLE", "MEDIA", "VOLUME", "LIGHT", "SETTINGS", "SHUTDOWN"}'  

  # im Boot/Shutdownvorgang true
  - id: is_blocked
    type: bool
    restore_value: no
    initial_value: 'false' 
  # Speichert den aktuell ausgewählten (fokussierten) Seitenindex im Menü (1..5)
  - id: current_page_index
    type: int
    restore_value: no
    initial_value: '0'

script:
  # 1. Hauptskript zum Wechseln des Seitenindexes
  - id: set_page_index
    mode: restart # Falls schnell hintereinander gedreht wird, bricht es alte Instanzen ab
    parameters:
      index: int
    then:
      - lambda: |-
          ESP_LOGD("navigation", "set_page_index %d", index);
          if(id(is_blocked)) return;

          int old_index = id(current_page_index);
          int new_index = index;
          
          // Bereich eingrenzen (Wechsel zwischen den Pages 1..5)
          if (new_index < 1) new_index = 5;
          if (new_index > 5) new_index = 1;
          
          // Nur ausführen, wenn sich der Index wirklich geändert hat
          if (new_index != old_index) {
            ESP_LOGD("navigation", "Wechsle Fokus von Index %d zu %d", old_index, new_index);
            
            // Führe Leave-Logik für alte Seite aus
            id(on_page_leave).execute(old_index);
            
            // Setze neuen globalen Index
            id(current_page_index) = new_index;
            
            // Führe Enter-Logik für neue Seite aus
            id(on_page_enter).execute(new_index);

            // Der eigentliche LVGL-Seitenwechsel wird für alle Indizes am Ende ausgeführt
            auto anim = LV_SCREEN_LOAD_ANIM_FADE_ON;
            if (index == old_index+1) {
              anim = LV_SCREEN_LOAD_ANIM_MOVE_LEFT;
            } else if (index == old_index-1) {
              anim = LV_SCREEN_LOAD_ANIM_MOVE_RIGHT;
            }
            id(my_lvgl).show_page(new_index, anim, 250);

          } else {
            ESP_LOGD("navigation", "Seite schon da!!!");
          }
      - lvgl.label.update:
          id: widget_title_label    
          text: !lambda |-
            int idx = id(current_page_index);
            return id(page_text).at(idx).c_str();

  # 2. Wird aufgerufen, wenn eine Seite im Fokus verlassen wird
  - id: on_page_leave
    parameters:
      index: int
    then:
      - lambda: |-
          ESP_LOGD("navigation", "Verlasse Seite Index: %d", index);
          // Hier später z.B. visuelle Highlights/Rahmen der alten Seite im Menü entfernen

  # 3. Wird aufgerufen, wenn eine neue Seite in den Fokus rückt (beim Drehen)
  - id: on_page_enter
    parameters:
      index: int
    then:
      - lambda: |-
          switch (index) {
            case 0: // PAGE_BOOT
              break;

            case 1: // PAGE_IDLE
              break;

            case 2: // PAGE_MEDIA
              break;

            case 3: // PAGE_VOLUME
              break;

            case 4: // PAGE_LIGHT
              break;

            case 5: // PAGE_SETTINGS
              break;

            case 99: // PAGE_SHUTDOWN
              break;

            default:
              ESP_LOGW("navigation", "Keine spezielle Initialisierung für Index %d", index);
              break;
          }


  # 4. Wird aufgerufen, wenn der Button geklickt wird (Aktivierung der Seite)
  - id: on_page_activate
    parameters:
      index: int
    then:
      - lambda: |-
          ESP_LOGI("navigation", "AKTIVIERE Seite Index: %d", index);
          // Hier kommt die Logik rein, was PASSIERT, wenn die Seite aktiv ist.
          // Z.B. "Subpages umschalten" für IDLE/SETTINGS oder "Play/Pause" für MEDIA.
