# common/bme280.yaml
substitutions:
  # climate BME280
  bme_addr:      "0x76"
  # VCC: 3V3
  # sda, scl vom i2c_bus

sensor:
  - platform: bme280_i2c
    id: climate_id
    update_interval: 60s
    address: 0x76
    temperature:
      id: room_temp
      name: Temperature
      device_class: temperature
      state_class: measurement      
    humidity:
      id: room_hum
      name: Humidity
      device_class: humidity
      state_class: measurement      
    pressure:
      id: room_press
      name: Pressure
      device_class: atmospheric_pressure
      state_class: measurement

esphome:
  on_boot:
    - priority: 250
      then:
      - lambda: |-
          ESP_LOGI(__FILE__, "Register Updater Scripts");
          id(idle_updater_scripts).push_back([]() { id(update_temp).execute(); });
          id(idle_updater_scripts).push_back([]() { id(update_hum).execute(); });
          id(idle_updater_scripts).push_back([]() { id(update_press).execute(); });

script:
  - id: update_temp
    then:
      - lambda: |-
          ESP_LOGD(__FILE__, "update_temp");
          id(idle_message1) = str_snprintf("%.1f °C", 32, id(room_temp).state);
  - id: update_hum
    then:
      - lambda: |-          
          ESP_LOGD(__FILE__, "update_hum");
          id(idle_message1) = str_snprintf("%.0f%% rF", 32, id(room_hum).state);
  - id: update_press
    then:
      - lambda: |-
          ESP_LOGD(__FILE__, "update_press");
          id(idle_message1) = str_snprintf("%.0f hPa", 32, id(room_press).state);

