# common/bme280.yaml
substitutions:
  # Climate HTU21
  bme_addr:      "0x76"
  # VCC: 3V3
  # sda, scl vom i2c_bus

sensor:
  - platform: htu21d
    id: climate_id
    update_interval: 60s
    address: 0x40
    temperature:
      id: room_temp
      name: "Temperature"
      device_class: temperature
      state_class: measurement
    humidity:
      id: room_hum
      name: "Humidity"
      device_class: humidity
      state_class: measurement
    heater:
      id: room_heater
      name: "Heater"
      state_class: measurement

esphome:
  on_boot:
    - priority: 250
      then:
      - lambda: |-
          ESP_LOGI(__FILE__, "Register Updater Scripts");
          id(idle_updater_scripts).push_back([]() { id(update_temp).execute(); });
          id(idle_updater_scripts).push_back([]() { id(update_hum).execute(); });

script:
  - id: update_temp
    then:
      - lambda: |-
          ESP_LOGD(__FILE__, "update_temp");
          id(idle_message1) = str_snprintf("%.1f °C", 32, id(room_temp).state);
  - id: update_hum
    then:
      - lambda: |-          
          ESP_LOGD(__FILE__, "update_hum");
          id(idle_message1) = str_snprintf("%.0f%% rF", 32, id(room_hum).state);

# switch:
#   - platform: template
#     id: htu21_heater
#     name: "htu21 freibrennen"
#     icon: "mdi:fire"
#     optimistic: true
#     lambda: |-
#       return id(climate_id).is_heater_enabled();
#     turn_on_action:
#       - logger.log: "htu21 Heater on"
#       - lambda: |-
#           id(climate_id).set_heater_level(4);
#           id(climate_id).set_heater(true);
#       # Wartet 5 Minuten (300 Sekunden)
#       - delay: 30s
#       - logger.log: "htu21 Heater off"
#       - lambda: |-
#           id(climate_id).set_heater_level(0);
#           id(climate_id).set_heater(false);
#       # Schaltet den Schalter im Dashboard wieder auf AUS
#       - switch.turn_off: htu21_heater
#     turn_off_action:
#       - logger.log: "htu21 Heater off"
#       - lambda: |-
#           id(climate_id).set_heater_level(0);
#           id(climate_id).set_heater(false);
