# common/scripts.yaml
sensor:
  # Die Dummys als Fallback (liefern standardmäßig "nan"). bme280.yaml muss danach inkludiert werden, um die echten Sensoren zu aktivieren.
  - platform: template
    id: room_temp
  - platform: template
    id: room_hum
  - platform: template
    id: room_press
  - platform: template
    id: room_heater

script:
####################### functions
  - id: update_data
    then:
      - lambda: |-
          auto timers = id(va).get_timers();
          const esphome::voice_assistant::Timer* active_timers[3] = {nullptr, nullptr, nullptr};
          int active_timer_count = 0;
          for (const auto &t : timers) {
              if (t.is_active) {
                  active_timer_count++;

                  // Direktes Einsortieren ohne Hilfsvariable
                  if (active_timers[0] == nullptr || t.seconds_left < active_timers[0]->seconds_left) {
                      active_timers[2] = active_timers[1];
                      active_timers[1] = active_timers[0];
                      active_timers[0] = &t;
                  } else if (active_timers[1] == nullptr || t.seconds_left < active_timers[1]->seconds_left) {
                      active_timers[2] = active_timers[1];
                      active_timers[1] = &t;
                  } else if (active_timers[2] == nullptr || t.seconds_left < active_timers[2]->seconds_left) {
                      active_timers[2] = &t;
                  }
              }
          }

          id(status_symbols)[0] =
            !id(wifi_id).is_connected() ? nullptr :
            id(wifi_rssi).state > -55   ? id(symbol_wifi_4) :
            id(wifi_rssi).state > -65   ? id(symbol_wifi_3) :
            id(wifi_rssi).state > -75   ? id(symbol_wifi_2) : 
                                          id(symbol_wifi_1);
          
          id(status_symbols)[1] =
            !id(api_id).is_connected()              ? nullptr :
            id(va).get_api_connection() != nullptr ? id(symbol_va) : 
                                                      id(symbol_api);
          
          id(status_symbols)[2] = 
            id(media_player_id).state == media_player::MEDIA_PLAYER_STATE_ANNOUNCING ? id(symbol_mp_announce) :
            id(hw_speaker)->get_mute_state()                                         ? id(symbol_mute) :
            id(media_player_id).state == media_player::MEDIA_PLAYER_STATE_PLAYING    ? id(symbol_mp_play) :
            id(media_player_id).state == media_player::MEDIA_PLAYER_STATE_PAUSED     ? id(symbol_mp_pause) :
            id(media_player_id).state == media_player::MEDIA_PLAYER_STATE_IDLE       ? id(symbol_mp_idle) :
                                                                                       nullptr;
          
          id(status_symbols)[3] =
            active_timer_count > 0              ? id(symbol_timer) :
            id(hw_microphone)->get_mute_state() ? id(symbol_deaf) : 
                                                  nullptr;


          // 1. ZENTRALER RESET (Failsafe)
          // Setzt alle Texte standardmäßig leer. Ein case schreibt nur noch, was er wirklich braucht.
          id(page_info_start_time) = 0;
          id(idle_message1) = "";
          id(idle_message2) = "";
          id(idle_message3) = "";
          
          // 2. CONTENT MODES (Nur wenn kein Overlay aktiv ist)
          if (id(overlay_mode) == ${OVERLAY_NONE}) {
            id(title_text) = id(content_mode_text)[id(content_mode)];
          
            switch (id(content_mode)) {
              case ${CONTENT_BOOT}:
                id(image_icon)    = id(logo_esphome);
                id(idle_message1) = "${version}";
                #include <esp_idf_version.h>
                id(idle_message2) = IDF_VER;
                break;
          
              case ${CONTENT_IDLE}: {
                id(image_icon) = nullptr;
                static const char* weekdays[] = {"Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"};
                auto now = id(esptime).now();
                
                int max_pages = 3;
                #ifdef HAVE_ENVIRONMENT_TEMP
                max_pages ++;
                #endif
                #ifdef HAVE_ENVIRONMENT_HUM
                max_pages ++;
                #endif
                #ifdef HAVE_ENVIRONMENT_PRESS
                max_pages ++;
                #endif

                int page_duration = id(page_info_duration).state * 1000;
                int idx = (millis() / page_duration) % max_pages;
                if (active_timer_count > 0)
                  idx = -1;
                else
                  id(page_info_start_time) = millis();
                
                switch (idx) {
                  case -1: 
                    if (active_timer_count == 0) {
                        id(idle_message1) = "Keine Timer";
                    }
                    if (active_timer_count >= 1 && active_timers[0] != nullptr) {
                        std::string name1 = active_timers[0]->name.empty() ? "Timer" : active_timers[0]->name;
                        id(idle_message1) = str_sprintf("%s: %lu s", name1.c_str(), active_timers[0]->seconds_left);
                    }
                    if (active_timer_count >= 2 && active_timers[1] != nullptr) {
                        std::string name2 = active_timers[1]->name.empty() ? "Timer" : active_timers[1]->name;
                        id(idle_message2) = str_sprintf("%s: %lu s", name2.c_str(), active_timers[1]->seconds_left);
                    }
                    if (active_timer_count == 3 && active_timers[2] != nullptr) {
                        std::string name3 = active_timers[2]->name.empty() ? "Timer" : active_timers[2]->name;
                        id(idle_message3) = str_sprintf("%s: %lu s", name3.c_str(), active_timers[2]->seconds_left);
                    }
                    if (active_timer_count > 3) {
                        id(idle_message3) = str_sprintf("%d Timer", active_timer_count);
                    }
                    break;
                  case 0: id(idle_message1) = str_snprintf("%02d:%02d", 32, now.hour, now.minute); break;
                  case 1: id(idle_message1) = str_snprintf("%02d.%02d.%02d", 32, now.day_of_month, now.month, now.year % 100); break;
                  case 2: id(idle_message1) = str_snprintf("%s", 32, weekdays[now.day_of_week - 1]);
                          id(idle_message2) = str_snprintf("%02d.%02d.%02d", 32, now.day_of_month, now.month, now.year % 100); break;
                #ifdef HAVE_ENVIRONMENT_TEMP
                  case 3: id(idle_message1) = str_snprintf("%.1f °C", 32, id(room_temp).state); break;
                #endif
                #ifdef HAVE_ENVIRONMENT_HUM
                  case 4: id(idle_message1) = str_snprintf("%.0f%% rF", 32, id(room_hum).state); break;
                #endif
                #ifdef HAVE_ENVIRONMENT_PRESS
                  case 5: id(idle_message1) = str_snprintf("%.0f hPa", 32, id(room_press).state); break;
                #endif
                }
                break;                
              }
          
              case ${CONTENT_PLAY}:
              case ${CONTENT_PAUSE}: // Zusammengefasst, da textlich identisch
                //id(image_icon)    = (id(content_mode) == ${CONTENT_PLAY}) ? id(icon_play) : id(icon_pause);
                id(image_icon) = nullptr;
                id(idle_message1) = id(media_album_name).state;
                id(idle_message2) = id(media_title).state;
                id(idle_message3) = id(media_artist).state;
                break;
          
              case ${CONTENT_LISTEN}:
                id(image_icon)    = id(icon_listen);
                id(idle_message1) = "Ja bitte";
                break;
          
              case ${CONTENT_THINK}:
                id(image_icon)    = id(icon_think);
                id(idle_message1) = id(command_message).empty() ? "denke ..." : id(command_message);
                break;
            }
          }
          
          // 3. OVERLAY MODES (Überschreiben ggf. Titel, Icon und Texte)
          switch (id(overlay_mode)) {
            case ${OVERLAY_VOLUME}:
              id(title_text)    = id(overlay_mode_text)[id(overlay_mode)];
              id(idle_message1) = id(media_player_id).is_muted() ? "MUTE" : str_snprintf(" VOL %.0f", 32, id(media_player_id).volume * 100.0f);
              break;
          
            case ${OVERLAY_ERROR}:
              id(title_text)    = id(overlay_mode_text)[id(overlay_mode)];
              id(image_icon)    = id(icon_error);
              id(idle_message1) = id(error_code);
              id(idle_message2) = id(error_message);
              break;
          
            case ${OVERLAY_ALARM}:
              id(title_text)    = id(overlay_mode_text)[id(overlay_mode)];
              id(image_icon)    = id(icon_alarm);
              id(idle_message1) = "Timer beendet";
              break;
              
            case ${OVERLAY_ANNOUNCE}: // Zusammengefasst, da identische Logik
              ESP_LOGD("custom", "show_announce_overlay: \"%s\" : \"%s\"", id(command_message).c_str(), id(announce_message).c_str());
              id(title_text)    = id(overlay_mode_text)[id(overlay_mode)];
              id(image_icon)    = id(icon_announce);
              id(idle_message1) = id(command_message);
              id(idle_message2) = id(announce_message);
              break;
          }
          
          // 4. DISPLAY DIREKT AKTUALISIEREN
          id(display_id)->update();

  - id: play_ui_sound
    mode: parallel
    parameters:
      sound_file: "audio::AudioFile*"
    then:      
      - lambda: |-
          std::string file_name = "Unbekannt";
          for (const auto &nf : esphome::audio_file::get_named_audio_files()) {
            if (nf.file == sound_file) {
              file_name = nf.file_id;
              break;
            }
          }      
          ESP_LOGI("UI-Sound", "play '%s'", file_name.c_str());
          id(ui_sound_player_id).play_file(sound_file, true, true);

  - id: set_content_mode
    parameters: 
      mode: int
    then:
      - logger.log:
          level: INFO
          format: "script set_content_mode %d"
          args: [ mode ]
      - lambda: |-
          // in der Bootphase wird nix geschaltet
          if (id(is_booting)) return;

          // Mode setzen
          id(content_mode) = mode;
          // mit HA synchronisieren
          id(content_mode_select).publish_state(mode);

          if (id(overlay_mode) != ${OVERLAY_NONE}) return;

            // LED-Effekt auswählen -- CONTENT_MODE
            std::string effect = "Effect CONTENT_" + std::to_string(mode);
            id(ledstrip_id).turn_on().set_effect(effect).perform();

          id(update_data).execute();
  - id: set_overlay_mode
    parameters:
      mode: int
    then:
      - logger.log:
          level: INFO
          format: "script set_overlay_mode %d"
          args: [ mode ]
      - lambda: |-
          // in der Bootphase wird nix geschaltet
          if (id(is_booting)) return;

          // Mode setzen
          id(overlay_mode) = mode;
          // mit HA synchronisieren
          id(overlay_mode_select).publish_state(mode);

          if(id(overlay_mode) == ${OVERLAY_NONE}) {
            mode = id(content_mode);
            // LED-Effekt auswählen -- CONTENT_MODE
            std::string effect = "Effect CONTENT_" + std::to_string(mode);
            id(ledstrip_id).turn_on().set_effect(effect).perform();
          } else {
            // LED-Effekt auswählen -- OVERLAY_MODE
            std::string effect = "Effect OVERLAY_" + std::to_string(mode);
            id(ledstrip_id).turn_on().set_effect(effect).perform();
          }

          id(update_data).execute();
          
  - id: show_volume_overlay
    mode: restart
    then:
      - logger.log:
          level: INFO
          format: "script show_volume_overlay"
      - lambda: |-
          id(set_overlay_mode).execute(${OVERLAY_VOLUME});
      - delay: 5s
      - lambda: |-
          id(set_overlay_mode).execute(${OVERLAY_NONE});
  - id: show_error_overlay
    mode: restart
    then:
      - logger.log:          
          level: INFO
          format: "script show_error_overlay"
      - lambda: |-
          id(set_overlay_mode).execute(${OVERLAY_ERROR});
      - delay: 5s
      - lambda: |-
          id(set_overlay_mode).execute(${OVERLAY_NONE});
  - id: show_alarm_overlay
    mode: restart
    then:
      - logger.log:          
          level: INFO
          format: "script show_alarm_overlay"
      - lambda: |-
          id(set_overlay_mode).execute(${OVERLAY_ALARM});
      - script.execute:
          id: play_ui_sound
          sound_file: snd_timer_alarm
      - delay: 3s
      - script.execute:
          id: play_ui_sound
          sound_file: snd_timer_alarm
      - delay: 3s
      - lambda: |-
          id(set_overlay_mode).execute(${OVERLAY_NONE});
  - id: show_announce_overlay
    mode: restart
    then:
      - logger.log:
          level: INFO
          format: "script show_announce_overlay"
      - lambda: |-
          id(set_overlay_mode).execute(${OVERLAY_ANNOUNCE});

      # Warten bis Announcement wirklich gestartet ist
      - wait_until:
          condition:
            media_player.is_announcing: media_player_id
          timeout: 5s

      # Warten bis Announcement vorbei ist
      - wait_until:
          condition:
            not:
              media_player.is_announcing: media_player_id
          timeout: 25s

      - lambda: |-
          // Overlay ausschalten
          id(set_overlay_mode).execute(${OVERLAY_NONE});

          



          


        
