substitutions:
  version: "0.0.7"

  # LED strip
  ledstrip_pin: "GPIO8"
  ledstrip_count: "10"
  # VCC: 5V

  # Buttons
  btn_1_pin: "GPIO15"
  btn_2_pin: "GPIO16"
  btn_3_pin: "GPIO17"
  btn_4_pin: "GPIO18"
  # VCC: 3V3

  # I2C bus
  i2c_sda_pin: "GPIO1"
  i2c_scl_pin: "GPIO2"  
  # VCC: 3V3

  # Environment BME280
  bme_addr:      "0x76"
  # VCC: 3V3 bis 5V

  # Display OLED SSD1306
  ssd_addr:      "0x3C"
  # VCC: 3V3 bis 5V

esphome:
  min_version: 2026.6.5
  project:
    name: "hufi.test0"
    version: ${version}
  on_boot:
    priority: -100
    then:
      - light.turn_on:
          id: ledstrip_id
          effect: "Rainbow"

light:
  - platform: esp32_rmt_led_strip
    id: ledstrip_id
    name: LED Status
    pin: ${ledstrip_pin}
    chipset: WS2812
    num_leds: ${ledstrip_count}
    rgb_order: GRB
    restore_mode: RESTORE_AND_ON
    icon: "mdi:led-strip"
    max_refresh_rate: 30ms
    use_dma: true
    use_psram: true
    effects:
      - addressable_scan:
          name: Scan slow
          move_interval: 0.2s
          scan_width: 3
      - addressable_rainbow:
          speed: 8
          width: 12
          name: Rainbow
      - addressable_twinkle:
          name: Twinkle
          progress_interval: 4ms
          twinkle_probability: 5%
      - addressable_color_wipe:
          name: Color Wipe
          add_led_interval: 0.1s

button:
  - platform: restart
    name: "Restart"
    on_press:
      then:
        - lambda: |-
            #ifdef USE_SAFE_MODE
            global_safe_mode->clean_shutdown();
            #endif

binary_sensor:
  - platform: gpio
    id: btn_up_id
    pin:
      number: ${btn_1_pin}
    on_multi_click:
     # --- EINFACHKLICK ---
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.5s
        then:
          - logger.log: "on_btn_1_single_click"

      # --- DOPPELKLICK ---
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at least 0.5s
        then:
          - logger.log: "on_btn_1_double_click"

      # --- LANGER KLICK ---
      - timing:
          - ON for at least 1.0s
        then:
          - logger.log: "on_btn_1_long_click"    
  - platform: gpio
    id: btn_down_id
    pin:
      number: ${btn_2_pin}
      allow_other_uses: false
    
    on_multi_click:
     # --- EINFACHKLICK ---
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.5s
        then:
          - logger.log: "on_btn_2_single_click"

      # --- DOPPELKLICK ---
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at least 0.5s
        then:
          - logger.log: "on_btn_2_double_click"

      # --- LANGER KLICK ---
      - timing:
          - ON for at least 1.0s
        then:
          - logger.log: "on_btn_2_long_click"    
  - platform: gpio
    id: btn_left_id
    pin:
      number: ${btn_3_pin}
      allow_other_uses: false
    on_multi_click:
     # --- EINFACHKLICK ---
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.5s
        then:
          - logger.log: "on_btn_3_single_click"

      # --- DOPPELKLICK ---
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at least 0.5s
        then:
          - logger.log: "on_btn_3_double_click"

      # --- LANGER KLICK ---
      - timing:
          - ON for at least 1.0s
        then:
          - logger.log: "on_btn_3_long_click"    
  - platform: gpio
    id: btn_right_id
    pin:
      number: ${btn_4_pin}
      allow_other_uses: false
    on_multi_click:
     # --- EINFACHKLICK ---
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.5s
        then:
          - logger.log: "on_btn_4_single_click"

      # --- DOPPELKLICK ---
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at least 0.5s
        then:
          - logger.log: "on_btn_4_double_click"

      # --- LANGER KLICK ---
      - timing:
          - ON for at least 1.0s
        then:
          - logger.log: "on_btn_4_long_click"    

text_sensor:
  # Wifi Informationen
  - platform: wifi_info
    id: wifi_info
    ip_address:
      name: "IP"
      icon: "mdi:wifi"
    ssid:
      name: "SSID"
      icon: "mdi:wifi"
    bssid:
      name: "BSSID"
      icon: "mdi:wifi"
    mac_address:
      name: "Mac"
      icon: "mdi:wifi"
    dns_address:
      name: "DNS"
      icon: "mdi:wifi"
    power_save_mode:
      name: "Power Save"
      icon: "mdi:wifi"
           
i2c:
  - id: i2c_bus
    sda: ${i2c_sda_pin}
    scl: ${i2c_scl_pin}
    scan: true
    frequency: 400kHz

sensor:
  # Wifi Informationen
  - platform: wifi_signal
    id: wifi_rssi
    name: "WiFi Signal dB"
    update_interval: 30s
  - platform: template
    id: wifi_channel
    name: "Channel"
    icon: "mdi:wifi-marker"
    entity_category: diagnostic
    lambda: |-
      if (id(wifi_id).is_connected())
        return id(wifi_id).get_wifi_channel();
      return -1;    
    update_interval: 30s      
  - platform: bme280_i2c
    id: envir_id
    address: ${bme_addr}
    temperature:
      id: room_temp
      name: Temperature
      device_class: temperature
      state_class: measurement      
    humidity:
      id: room_hum
      name: Humidity
      device_class: humidity
      state_class: measurement      
    pressure:
      id: room_press
      name: Pressure
      device_class: atmospheric_pressure
      state_class: measurement

###### Video
font:
  - id: font_medium
    file:
      type: gfonts
      family: Roboto Condensed
      weight: 300
    size: 14
    glyphs:
      - äöüÄÖÜß°
    glyphsets:
      - GF_Latin_Kernel
  - id: font_large
    file:
      type: gfonts
      family: Roboto Condensed
      weight: 300
    size: 21
    glyphs:
      - äöüÄÖÜß°
    glyphsets:
      - GF_Latin_Kernel
  - id: font_huge
    file:
      type: gfonts
      family: Roboto Condensed
      weight: 300
    size: 28
    glyphs:
      - äöüÄÖÜß°
    glyphsets:
      - GF_Latin_Kernel
    
display:
  - platform: ssd1306_i2c
    model: SSD1306_128X64
    id: display_id
    address: ${ssd_addr}
    update_interval: 50ms
    lambda: |-
      it.print(64, 40, id(font_medium), TextAlign::CENTER, "Jetzt gehts");
