# common/voice-satellite.yaml
######################### Configuration

substitutions:
  version: "0.7.0"

  # Display Modes
  CONTENT_BOOT:     0
  CONTENT_IDLE:     1
  CONTENT_PLAY:     2
  CONTENT_PAUSE:    3
  CONTENT_LISTEN:   4
  CONTENT_THINK:    5

  OVERLAY_NONE:     0
  OVERLAY_VOLUME:   1
  OVERLAY_ERROR:    2
  OVERLAY_ALARM:    3
  OVERLAY_ANNOUNCE: 4

esphome:
  project:
    name: "hufi.smart_speaker"
    version: ${version}
  on_boot:
    - priority: 600
      then:
        - script.execute: on_esp_boot_600
    - priority: 250
      then:
        - script.execute: on_esp_boot_250
    - priority: 200
      then:
        - script.execute: on_esp_boot_200
    - priority: -100
      then:
        - script.execute: on_esp_boot_minus100
            
    
# Enable Home Assistant API
api:
  on_client_connected:
    - script.execute: on_api_client_connect
  on_client_disconnected:
    - script.execute: on_api_client_disconnect

wifi:
  on_connect:
    - script.execute: on_wifi_connect
  on_disconnect:
    - script.execute: on_wifi_disconnect

globals:
  - id: is_ducking
    type: bool
    initial_value: "false"
    
  - id: content_mode
    type: int
    initial_value: "0"    
  - id: overlay_mode
    type: int
    initial_value: "0"
  - id: content_mode_text
    type: std::vector<std::string>
    initial_value: '{"BOOT", "IDLE", "PLAY", "PAUSE", "LISTEN", "THINK", "ANNOUNCE"}'  
  - id: overlay_mode_text
    type: std::vector<std::string>
    initial_value: '{"NONE", "VOLUME", "ERROR", "ALARM", "ANNOUNCE"}'  

  - id: command_message
    type: std::string
    initial_value: "\"command\""
  - id: intent_message
    type: std::string
    initial_value: "\"intent\""
  - id: announce_message
    type: std::string
    initial_value: "\"announce\""
  - id: url_message
    type: std::string
    initial_value: "\"url\""
  - id: alarm_message
    type: std::string
    initial_value: "\"alarm\""
  - id: error_code
    type: std::string
    initial_value: "\"code\""
  - id: error_message
    type: std::string
    initial_value: "\"error\""

########################## Components

time:
  - platform: homeassistant
    id: esptime
    on_time_sync: 
      then:
        - script.execute: on_time_time_sync

sun:
  id: sun_id
  latitude: !secret latitude
  longitude: !secret longitude

deep_sleep:
  id: deep_sleep_id
  wakeup_pin: 
    number: ${btn_1_pin}
    allow_other_uses: true
  wakeup_pin_mode: INVERT_WAKEUP

light:
  - id: !extend ledstrip_id
    effects:
      # Content Mode Effects
      # Effect CONTENT_BOOT
      - addressable_lambda:
          name: "Effect CONTENT_0" # BOOT
          update_interval: 50ms
          lambda: |-
            // Definiert die Geschwindigkeit und zwingt den Wert in eine Endlosschleife von 0 bis 255
            int wave_time = (millis() / 12) % 256;

            for (int i = 0; i < it.size(); i++) {
              // Berechnet den Helligkeitsverlauf basierend auf der LED-Position
              int v = wave_time + abs(i - it.size() / 2.0f) * 16;
              
              // Nutzt Modulo, damit die Welle endlos von außen nach innen "durchläuft"
              v = v % 256; 
              
              it[i] = Color(0, 0, v);
            }

      # Effect CONTENT_IDLE
      - addressable_lambda:
          name: "Effect CONTENT_1" # IDLE
          update_interval: 16ms
          lambda: |-
            auto color = id(idle_color);

            for (int i = 0; i < it.size(); i++) {
              it[i] = color;
            }

      # Effect CONTENT_PLAY
      - addressable_rainbow:
          name: "Effect CONTENT_2" # PLAY
          speed: 16
          width: 12
          
      # Effect CONTENT_PAUSE
      - addressable_lambda:
          name: "Effect CONTENT_3" # PAUSE
          update_interval: 50ms
          lambda: |-
            float t = (sin(millis() / 500.0f) + 1) / 2;  // langsames Atmen
            uint8_t y = 60 + (uint8_t)(t * 120);

            for (int i = 0; i < it.size(); i++) {
              it[i] = Color(y, y, 0);  // Gelb
            }
      # Effect CONTENT_LISTEN
      - addressable_lambda:
          name: "Effect CONTENT_4"  # LISTEN
          update_interval: 20ms
          lambda: |-
            const int count = it.size();
            const float t = millis() / 250.0f;   // Puls-Geschwindigkeit
            const float pulse = (sin(t) + 1.0f) * 0.5f;  // 0..1
      
            const float center = (count - 1) / 2.0f;     // Mitte der LEDs
      
            for (int i = 0; i < count; i++) {
              float d = fabsf(i - center);               // Abstand zur Mitte
              float falloff = 1.0f - (d / center);       // 1.0 in der Mitte, 0.0 außen
              if (falloff < 0.0f) falloff = 0.0f;
      
              int brightness = int( falloff * pulse * 255 );
      
              // Farbe: Cyan-Blau wie dein Listening-Effekt
              it[i] = Color(0, 64, brightness);
            }
      # Effect CONTENT_THINK
      - addressable_lambda:
          name: "Effect CONTENT_5" # THINK
          update_interval: 20ms
          lambda: |-
            int pos = (millis() / 40) % it.size();
            pos = it.size() - pos;
            for (int i = 0; i < it.size(); i++) {
              int d = abs(i - pos);
              int b = max(0, 150 - d * 40);
              it[i] = Color(b, 0, b);
            }

      # Overlay Mode Effects
      # Effect OVERLAY_NONE
      - addressable_lambda:
          name: "Effect OVERLAY_0"
          update_interval: 250ms
          lambda: |-
            for (int i = 0; i < it.size(); i++) {
              it[i] = Color(0,0,0);
            }
      # Effect OVERLAY_VOLUME
      - addressable_lambda:
          name: "Effect OVERLAY_1"
          update_interval: 20ms
          lambda: |-
            if (id(media_player_id).is_muted()) {
              float t = (millis() % 800) / 800.0f;
              float fade = (sin(t * 2 * 3.14159f) + 1) / 2;  // 0–1
              for (int i = 0; i < it.size(); i++) {
                it[i] = Color(0, 0, int(128 * fade));
              }
              return;
            }

            float index = id(media_player_id).volume * it.size();

            for (int i = 0; i < it.size(); i++) {
              float fade = std::clamp(index - i, 0.2f, 1.0f);
              // falschrum eingebaut
              it[i] = Color(0, int(127*fade), int(255*fade));
            }
      # Effect OVERLAY_ERROR
      - addressable_lambda:
          name: "Effect OVERLAY_2"
          update_interval: 40ms
          lambda: |-
            float t = (millis() % 800) / 800.0f;
            float b = (sin(t * 2 * 3.14159f) + 1) / 2;  // 0–1
            for (int i = 0; i < it.size(); i++) {
              it[i] = Color(int(200 * b), 0, 0);
            }
      # Effect CONTENT_ALARM
      - addressable_lambda:
          name: "Effect OVERLAY_3"
          update_interval: 50ms
          lambda: |-
            float t = (sin(millis() / 250.0f) + 1) / 2;  // langsames Atmen
            uint8_t y = 60 + (uint8_t)(t * 120);

            for (int i = 0; i < it.size(); i++) {
              it[i] = Color(0, y, 0);  // Rot
            }
      # Effect OVERLAY_ANNOUNCE
      - addressable_lambda:
          name: "Effect OVERLAY_4"
          update_interval: 20ms
          lambda: |-
            const int count = it.size();

            // Position des Scans (läuft von 0 bis count-1)
            int pos = (millis() / 40) % count;

            for (int i = 0; i < count; i++) {
              // Abstand zur Scan-Position
              int d = abs(i - pos);

              // Helligkeit abhängig vom Abstand (weicher Abfall)
              int b = max(0, 120 - d * 40);  // 120 = hell, 40 = Abfall pro LED

              it[i] = Color(b+75, b, b+75);  // Cyan-Blau
            }

######################################################################################

media_player:
  - id: !extend media_player_id

    on_announcement:
      - script.execute: on_media_player_announcement
    on_play:
      - script.execute: on_media_player_play
    on_pause:
      - script.execute: on_media_player_pause

    on_idle:
      - script.execute: on_media_player_idle
        
    on_turn_on:
      - script.execute: on_media_player_turn_on
    on_turn_off:
      - script.execute: on_media_player_turn_off
    on_mute:
      - script.execute: on_media_player_mute
    on_unmute:
      - script.execute: on_media_player_unmute
    on_volume:
      - if:
          condition:
            lambda: 'return !id(is_ducking);'
          then:
            - script.execute: on_media_player_volume
          else:
            logger.log: "on_media_player_volume: (skip while ducking)"
    on_state:
      - lambda: |-
          ESP_LOGW(__FILE__, "on_media_player_state: %s", media_player::media_player_state_to_string(id(media_player_id).state));

          switch (id(media_player_id).state) {
            case media_player::MEDIA_PLAYER_STATE_ANNOUNCING: {
              if (!id(is_ducking)) {
                ESP_LOGW(__FILE__, "enable ducking!!!!");
                id(media_mixing_input).apply_ducking(16, 300);
                id(is_ducking) = true;
              }
              break;
            }
            case media_player::MEDIA_PLAYER_STATE_PLAYING:
            case media_player::MEDIA_PLAYER_STATE_PAUSED:
            case media_player::MEDIA_PLAYER_STATE_IDLE: {
              if (id(is_ducking)) {
                ESP_LOGW(__FILE__, "disable ducking!!!!");
                id(media_mixing_input).apply_ducking(0, 300);
                id(is_ducking) = false;
              } else {
                ESP_LOGW(__FILE__, "no ducking skipped");
              }
              break;
            }
            case media_player::MEDIA_PLAYER_STATE_NONE:
            case media_player::MEDIA_PLAYER_STATE_OFF:
            case media_player::MEDIA_PLAYER_STATE_ON: {
              ESP_LOGW(__FILE__, "nothing");
              break;
            }
          }
      - script.execute: on_media_player_state

voice_assistant:

  on_client_connected: 
    - script.execute: on_voice_assistant_client_connected
  on_client_disconnected: 
    - script.execute: on_voice_assistant_client_disconnected
  on_idle: 
    - script.execute: on_voice_assistant_idle
  on_listening: 
    - script.execute: on_voice_assistant_listening
  on_start: 
    - script.execute: on_voice_assistant_start
    - globals.set: 
        id: command_message
        value: !lambda return "";
    - globals.set: 
        id: announce_message
        value: !lambda return "";
    - globals.set: 
        id: url_message
        value: !lambda return "";
    - globals.set: 
        id: error_code
        value: !lambda return "";
    - globals.set: 
        id: error_message
        value: !lambda return "";
    - globals.set: 
        id: intent_message
        value: !lambda return "";
      
  on_stt_end: 
    - globals.set: 
        id: command_message
        value: !lambda return x;
    - logger.log: 
        level: INFO
        format: "Command %s"
        args: [ id(command_message).c_str() ]
    - script.execute: on_voice_assistant_stt_end
  on_stt_vad_start:
    - script.execute: on_voice_assistant_stt_vad_start
  on_stt_vad_end:
    - script.execute: on_voice_assistant_stt_vad_end
      
  on_tts_start:
    - globals.set: 
        id: announce_message
        value: !lambda return x;    
    - logger.log: 
        level: INFO
        format: "Announce %s"
        args: [ id(announce_message).c_str() ]
    - script.execute: on_voice_assistant_tts_start
  on_tts_end: 
    - globals.set: 
        id: url_message
        value: !lambda return x;    
    - logger.log:
        level: INFO
        format: "URL %s"
        args: [ id(url_message).c_str() ]
    - script.execute: on_voice_assistant_tts_end
  on_end: 
    - logger.log:
        level: INFO
        format: "VA End"
    - wait_until: 
        condition:
          - not:
            - voice_assistant.is_running:
    - script.execute: on_voice_assistant_end
    - script.wait: on_voice_assistant_end
  on_error: 
    - globals.set: 
        id: error_code
        value: !lambda return code;
    - globals.set: 
        id: error_message
        value: !lambda return message;
    - script.execute: on_voice_assistant_error
    - script.wait: on_voice_assistant_error
  on_intent_start:
    - script.execute: on_voice_assistant_intent_start
  on_intent_progress:
    - globals.set: 
        id: intent_message
        value: !lambda return x;
    - logger.log:
        level: INFO
        format: "Intent %s"
        args: [ id(intent_message).c_str() ]
    - script.execute: on_voice_assistant_intent_progress
  on_intent_end:
    - script.execute: on_voice_assistant_intent_end

  on_timer_started:
    - script.execute:
        id: on_voice_assistant_timer_started
        timer_id: !lambda 'return timer.id;'
        timer_name: !lambda 'return timer.name;'
        timer_total_seconds: !lambda 'return timer.total_seconds;'
    - script.execute:
        id: update_data
  on_timer_finished:
    - script.execute:
        id: on_voice_assistant_timer_finished
        timer_id: !lambda 'return timer.id;'
        timer_name: !lambda 'return timer.name;'
        timer_total_seconds: !lambda 'return timer.total_seconds;'
    - script.execute:
        id: update_data
  on_timer_cancelled:
    - script.execute:
        id: on_voice_assistant_timer_cancelled
        timer_id: !lambda 'return timer.id;'
        timer_name: !lambda 'return timer.name;'
        timer_total_seconds: !lambda 'return timer.total_seconds;'
        timer_seconds_left: !lambda 'return timer.seconds_left;'
    - script.execute:
        id: update_data
  on_timer_updated:
    - script.execute:
        id: on_voice_assistant_timer_updated
        timer_id: !lambda 'return timer.id;'
        timer_name: !lambda 'return timer.name;'
        timer_is_active: !lambda 'return timer.is_active;'
        timer_total_seconds: !lambda 'return timer.total_seconds;'
        timer_seconds_left: !lambda 'return timer.seconds_left;'
    - script.execute:
        id: update_data
  on_timer_tick:
    - lambda: |-
        for (const auto &t : timers) {
          if (t.is_active) {
            // Wir rufen das Skript für jeden aktiven Timer direkt aus C++ auf
            id(on_voice_assistant_timer_tick).execute(t.id, t.name, t.total_seconds, t.seconds_left);
          }
        }  
    - script.execute:
        id: update_data
    
micro_wake_word:
        
  on_wake_word_detected:
    then:
      - script.execute:
          id: on_micro_wake_word_on_wake_word_detected
          ww: !lambda 'return wake_word;'

        
###################################### Automation

number:
  - platform: template
    id: content_mode_select
    name: "Content Mode"
    entity_category: diagnostic
    min_value: 0
    max_value: 5
    step: 1    
    initial_value: "${CONTENT_BOOT}"
    optimistic: True
    set_action:
      - lambda: |-
          id(set_content_mode).execute(x);
  - platform: template
    id: overlay_mode_select
    name: "Overlay Mode"
    entity_category: diagnostic
    min_value: 0
    max_value: 4
    step: 1
    initial_value: "${OVERLAY_NONE}"
    set_action:
      - lambda: |-
          id(set_overlay_mode).execute(x);

